name: Update AI Intelligence Data

on:
  schedule:
    # Run every Monday at 8:00 AM UTC (weekly updates)
    - cron: '0 8 * * 1'
  workflow_dispatch: # Allow manual triggering
  
jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create data update script
      run: |
        cat > update-data.js << 'EOF'
        const fs = require('fs');
        const path = require('path');
        
        // Simple data update script
        const updateData = async () => {
          try {
            const dataPath = path.join(__dirname, 'src', 'data', 'sampleData.js');
            const data = fs.readFileSync(dataPath, 'utf8');
            
            // Update timestamps
            const today = new Date().toISOString();
            const nextWeek = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
            
            // Update metadata
            const updatedData = data
              .replace(
                /lastUpdated: new Date\(\)\.toISOString\(\)/,
                `lastUpdated: "${today}"`
              )
              .replace(
                /nextUpdateScheduled: new Date\(Date\.now\(\) \+ 7 \* 24 \* 60 \* 60 \* 1000\)\.toISOString\(\)/,
                `nextUpdateScheduled: "${nextWeek}"`
              )
              .replace(
                /dataSource: "[^"]*"/,
                'dataSource: "Automated weekly update + API integration"'
              );
            
            fs.writeFileSync(dataPath, updatedData);
            console.log('Data updated successfully');
            
            // Create a summary of changes
            const summary = {
              timestamp: today,
              changes: [
                'Updated lastUpdated timestamp',
                'Updated nextUpdateScheduled timestamp',
                'Updated dataSource to reflect automated update'
              ],
              nextUpdate: nextWeek
            };
            
            fs.writeFileSync('update-summary.json', JSON.stringify(summary, null, 2));
            console.log('Update summary created');
            
          } catch (error) {
            console.error('Error updating data:', error);
            process.exit(1);
          }
        };
        
        updateData();
        EOF
        
    - name: Run data update
      run: node update-data.js
      
    - name: Check for GitHub API data
      run: |
        cat > fetch-github-data.js << 'EOF'
        const fs = require('fs');
        const https = require('https');
        
        const fetchGitHubData = async () => {
          try {
            const options = {
              hostname: 'api.github.com',
              path: '/search/repositories?q=ai+machine-learning+created:>2024-01-01&sort=stars&order=desc&per_page=5',
              method: 'GET',
              headers: {
                'User-Agent': 'AI-Intelligence-Agent',
                'Accept': 'application/vnd.github.v3+json'
              }
            };
            
            const req = https.request(options, (res) => {
              let data = '';
              res.on('data', (chunk) => data += chunk);
              res.on('end', () => {
                try {
                  const result = JSON.parse(data);
                  if (result.items) {
                    console.log(`Found ${result.items.length} new AI repositories`);
                    fs.writeFileSync('github-data.json', JSON.stringify(result, null, 2));
                  } else {
                    console.log('No new repositories found');
                  }
                } catch (error) {
                  console.error('Error parsing GitHub response:', error);
                }
              });
            });
            
            req.on('error', (error) => {
              console.error('Error fetching GitHub data:', error);
            });
            
            req.end();
            
          } catch (error) {
            console.error('Error in fetchGitHubData:', error);
          }
        };
        
        fetchGitHubData();
        EOF
        
        node fetch-github-data.js
        
    - name: Build application
      run: npm run build
      env:
        CI: false
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        
    - name: Commit updated data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "🤖 Automated weekly data update - $(date +'%Y-%m-%d')"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        
    - name: Create update notification
      run: |
        if [ -f "update-summary.json" ]; then
          echo "## 🤖 Automated Weekly Update" >> $GITHUB_STEP_SUMMARY
          echo "**Timestamp:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ✅ Successfully updated AI Intelligence data" >> $GITHUB_STEP_SUMMARY
          echo "**Changes:**" >> $GITHUB_STEP_SUMMARY
          echo "- Updated data timestamps" >> $GITHUB_STEP_SUMMARY
          echo "- Refreshed GitHub AI repository data" >> $GITHUB_STEP_SUMMARY
          echo "- Rebuilt and deployed application" >> $GITHUB_STEP_SUMMARY
          echo "**Next Update:** Next Monday at 8:00 AM UTC" >> $GITHUB_STEP_SUMMARY
          echo "**Dashboard:** https://e88-eqx.github.io/ai-intelligence-agent/" >> $GITHUB_STEP_SUMMARY
        fi